### All User Request

GET http://localhost:3000/users

### User Request

GET http://localhost:3000/users/1

### Post User

POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "Micheldu93",
    "email": "michelle@yolo.com",
    "last_name": "Dupont",
    "first_name": "Michel",
    "password": "king"

}

### User Request

DELETE  http://localhost:3000/users/8

### All Series Request

GET http://localhost:3000/series

### Serie Request

GET http://localhost:3000/series/3

### Post Serie

POST http://localhost:3000/series
Content-Type: application/json

{
    "title": "Berserk",
    "genre": "Seinen",
    "author": "Kentaro Miura",
    "format": "Manga",
    "user_id": "1"
}

// VOLUMES TESTS

### Volume Request

GET http://localhost:3000/series/2/volumes

### Post Volume

POST http://localhost:3000/series/2/volumes
Content-Type: application/json

{
    "volume_number": 4,
    "price": "14.50",
    "image_url": "https://example.com/bs4.jpg",
    "signed": true,
    "collector": false,
    "is_read": true,
    "publication_date": "2000-11-14T23:00:00.000Z",
    "series": { "id": 2 }
}